apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: three-tier

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: three-tier-backend:v1

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000
              name: http

          env:
            - name: DB_HOST
              value: mysql-service

            - name: DB_PORT
              value: "3306"

            - name: DB_NAME
              value: appdb

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20