name: Kubernetes Connection Test

on:
  push:
    branches:
      - main

jobs:
  kubernetes-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Kubernetes connection
        run: |
          kubectl config current-context
          kubectl get nodes
          kubectl get pods -n three-tier